"""adding filename field to post

Revision ID: 1c5a223f1d58
Revises: 90aa634530c8
Create Date: 2020-05-17 12:52:52.215414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5a223f1d58'
down_revision = '90aa634530c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('filename', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'filename')
    # ### end Alembic commands ###
