"""change 12:08

Revision ID: 2e5e5fb588cc
Revises: 38c19663d129
Create Date: 2020-05-15 12:05:16.120003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5e5fb588cc'
down_revision = '38c19663d129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', sa.String(length=140), nullable=True))
    with op.batch_alter_table('post') as batch_op:
    	batch_op.drop_column('body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'url')
    # ### end Alembic commands ###
