"""empty message

Revision ID: 362903955a4f
Revises: 569827ba38ee
Create Date: 2020-05-15 17:19:19.180578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362903955a4f'
down_revision = '569827ba38ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('url', sa.String(length=140), nullable=True))
    with op.batch_alter_table('post') as batch_op:
    	batch_op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
