"""change 12:06

Revision ID: 38c19663d129
Revises: 3d47285dc8cd
Create Date: 2020-05-15 12:03:52.490641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c19663d129'
down_revision = '3d47285dc8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=140), nullable=True))
    with op.batch_alter_table('post') as batch_op:
    	batch_op.drop_column('url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
