"""changing body to url

Revision ID: 3d47285dc8cd
Revises: bc40f1cc96a9
Create Date: 2020-05-15 11:57:57.693807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d47285dc8cd'
down_revision = 'bc40f1cc96a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
    	batch_op.drop_column('body')
    op.add_column('post', sa.Column('url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'url')
    # ### end Alembic commands ###
