"""changes last

Revision ID: 3d9f4cd4edd1
Revises: 8b05b368483d
Create Date: 2020-05-15 11:31:08.026242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9f4cd4edd1'
down_revision = '8b05b368483d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body2', sa.String(length=140), nullable=True))
    op.drop_column('post', 'bod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('bod', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'body2')
    # ### end Alembic commands ###
