"""changes adding name

Revision ID: 496ac3a31c9b
Revises: 977b77d9a8e8
Create Date: 2020-05-15 11:46:29.432222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496ac3a31c9b'
down_revision = '977b77d9a8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
