"""adding url to post

Revision ID: 569827ba38ee
Revises: aa1ef7411da0
Create Date: 2020-05-15 13:52:18.884909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569827ba38ee'
down_revision = 'aa1ef7411da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'url')
    # ### end Alembic commands ###
