"""changes after head

Revision ID: 8b05b368483d
Revises: d8627da559bc
Create Date: 2020-05-15 11:02:22.134514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b05b368483d'
down_revision = 'd8627da559bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.add_column('post', sa.Column('bod', sa.String(length=140), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'bod')
    op.drop_table('followers')
    # ### end Alembic commands ###
