"""changing post db final cut

Revision ID: 90aa634530c8
Revises: b217864db0fc
Create Date: 2020-05-15 17:26:57.150535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90aa634530c8'
down_revision = 'b217864db0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
    	batch_op.drop_column('url2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url2', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
