"""changes last 2

Revision ID: 9664b2bd99db
Revises: 3d9f4cd4edd1
Create Date: 2020-05-15 11:36:02.095885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9664b2bd99db'
down_revision = '3d9f4cd4edd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'bod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('bod', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
