"""changes last 999

Revision ID: 977b77d9a8e8
Revises: 9664b2bd99db
Create Date: 2020-05-15 11:38:41.990267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977b77d9a8e8'
down_revision = '9664b2bd99db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
	    batch_op.drop_column('body')
	    batch_op.drop_column('bod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('bod', sa.VARCHAR(length=140), nullable=True))
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
