"""deleting time

Revision ID: ae01e3ccfc1e
Revises: 496ac3a31c9b
Create Date: 2020-05-15 11:47:52.409887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae01e3ccfc1e'
down_revision = '496ac3a31c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_timestamp', table_name='post')
    with op.batch_alter_table('post') as batch_op:
	    batch_op.drop_column('timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###
