"""adding img stucture

Revision ID: d8627da559bc
Revises: b3af494d69ca
Create Date: 2020-05-15 10:22:49.837898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8627da559bc'
down_revision = 'b3af494d69ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', sa.String(length=120), nullable=False))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'url')
    # ### end Alembic commands ###
